### PR TITLE
implement a dynamic inventory for ansible

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@dmsimard would you mind reviewing/testing this? :)

**Comment by ehelms** [comment]
Bump -- would love to get a review on this

**Comment by bstinsonmhk** [comment]
@evgeni do you have usage docs for this?

I'll see if I can get this tested on our staging setup

**Comment by evgeni** [comment]
@bstinsonmhk I have updated the script with a small documentation section, hopefully this can get you started.

**Comment by evgeni** [comment]
also, a few notes that IMHO don't belong into the "official" docs:

```
/home/foreman/evgeni/ansible/ is a checkout of https://github.com/ansible/ansible
/home/foreman/evgeni/python-cicoclient/ is a checkout of this PR

# this is only needed because I run Ansible from a Git checkout, not installed from RPM/pip
[foreman@slave01 ~]$ cd ~/evgeni/ansible/
[foreman@slave01 ansible]$ . ./hacking/env-setup
Setting up Ansible to run out of checkout...

PATH=/home/foreman/evgeni/ansible/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/foreman/.local/bin:/home/foreman/bin
PYTHONPATH=/home/foreman/evgeni/ansible/lib
MANPATH=/home/foreman/evgeni/ansible/docs/man:/usr/local/share/man:/usr/share/man

Remember, you may wish to specify your host file with -i

Done!

# adding my local cicoclient checkout to PYTHONPATH, the one installed on the machine does not do API KEY auto detection
[foreman@slave01 ansible]$ export PYTHONPATH=/home/foreman/evgeni/ansible/lib:/home/foreman/evgeni/python-cicoclient/

# we're talking "cloud" here, so the keys will never match
[foreman@slave01 ansible]$ export ANSIBLE_HOST_KEY_CHECKING=False

# run the ping module on all machines
[foreman@slave01 ansible]$ ansible -i /home/foreman/evgeni/python-cicoclient/cicoclient/ansible/cico_inventory.py -m ping all
n60.pufty | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
```

**Comment by evgeni** [comment]
@bstinsonmhk did you have a chance to look at this?

**Comment by evgeni** [comment]
moving to draft, as this should be reimplemented as an inventory plugin, instead of inventory script

**Comment by evgeni** [comment]
cico is dead, long live cico!

**Pull request closed without merging**
